##################################################
# Makefile of pmtestx.asm (x=[1,2,3...])
##################################################

.PHONY : clean

all : 9 9a 9b 9c
9 :
	nasm pmtest9.asm -o pmtest9.com
	cp -v pmtest9.com /Volumes/AAA/
9a :
	nasm pmtest9a.asm -o pmtest9a.com
	cp -v pmtest9a.com /Volumes/AAA/
9b :
	nasm pmtest9b.asm -o pmtest9b.com
	cp -v pmtest9b.com /Volumes/AAA/

9c :
	nasm pmtest9c.asm -o pmtest9c.com
	cp -v pmtest9c.com /Volumes/AAA/

clean :
	rm *.com
